
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 🛎️ checkout
      uses: actions/checkout@v2

    - name: 🔧 set up node
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: 📦 npm install
      shell: bash
      run: npm ci

    - name: 📦 build
      shell: bash
      run: npm run build

    - name: 📦 test
      shell: bash
      run: npm test

